console.time("time taken")
console.log("Hello Parmeshwar")
console.log({harry:'this',marks:'99'})
console.table({harry:'this',marks:'99'})
console.warn("this is warniing")
console.error("this is error")
console.assert(2<1,"this is not possible")
console.timeEnd("time taken")
// console.clear()
